spring:
  datasource:
    url: jdbc:postgres://localhost:5433/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-description: "init"
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  cloud:
    config:
      override-system-properties: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8050